""""""""""
" pathogen

" .vim/bundle/plugin_nameを読み込むようにする
call pathogen#incubate()





""""""""""
" unite.vim

" 入力モードで開始する
let g:unite_enable_start_insert = 1

" 以下を候補とする。
"  - バッファ
"  - 最近使ったファイルの一覧
"  - ファイル
"  - ファイル（再帰検索）
" （buffer-nameをfilesにすると、/区切りでワイルドカードが自動的に付加される。）
nnoremap <silent> ,j :<C-u>Unite -buffer-name=files buffer file_mru<CR>
nnoremap <silent> ,cj :<C-u>UniteWithCurrentDir -buffer-name=files buffer<CR>
"nnoremap <silent> ,bj :<C-u>UniteWithBufferDir -buffer-name=files -prompt=%\  buffer file_mru<CR>

" ファイル
nnoremap <silent> ,f :<C-u>Unite -buffer-name=files file<CR>
nnoremap <silent> ,F :<C-u>Unite -buffer-name=files file file_rec<CR>

" バッファ
nnoremap <silent> ,b :<C-u>Unite buffer<CR>

" ブックマーク
nnoremap <silent> ,m :<C-u>Unite bookmark<CR>
" ブックマークを追加
nnoremap <silent> ,a :<C-u>UniteBookmarkAdd<CR>

" grep
nnoremap <silent> ,g :<C-u>Unite -no-quit grep -buffer-name=grep<CR>
nnoremap <silent> ,G :<C-u>Unite -no-quit grep -buffer-name=grep
" ソースコード内検索用grep
nnoremap <silent> ,s :<C-u>Unite -no-quit grep::--include='*.h'\ --include='*.hpp'\ --include='*.c'\ --include='*.cpp'\ --include='*.m'\ --include='*.mm'\ --include='*.inl'\  -buffer-name=grep<CR>
nnoremap <silent> ,S :<C-u>Unite -no-quit grep::--include='*.h'\ --include='*.hpp'\ --include='*.c'\ --include='*.cpp'\ --include='*.m'\ --include='*.mm'\ --include='*.inl'\  -buffer-name=grep

" バッファ内検索
nnoremap <silent> ,l :<C-u>Unite -no-quit line<CR>
nnoremap <silent> ,wl :<C-u>UniteWithCursorWord -no-quit line<CR>

" タグ
nnoremap <silent> ,t :<C-u>Unite tag -buffer-name=tag<CR>
nnoremap <silent> ,T :<C-u>Unite tag -buffer-name=tag
nnoremap <silent> ,wt :<C-u>UniteWithCursorWord -immediately tag -buffer-name=tag<CR>
nnoremap <silent> ,wT :<C-u>UniteWithCursorWord -immediately tag -buffer-name=tag

" Uniteバッファ
nnoremap <silent> ,r :<C-u>Unite resume<CR>

" キーマップ
nnoremap <silent> ,k :<C-u>Unite mapping<CR>

" アウトライン（未インストール）
"nnoremap <silent> <Space>o :<C-u>Unite outline<CR>

" ウィンドウを分割して開く
au FileType unite nnoremap <silent> <buffer> <expr> <C-S> unite#do_action('split')
au FileType unite inoremap <silent> <buffer> <expr> <C-S> unite#do_action('split')

" ウィンドウを縦に分割して開く
au FileType unite nnoremap <silent> <buffer> <expr> <C-V> unite#do_action('vsplit')
au FileType unite inoremap <silent> <buffer> <expr> <C-V> unite#do_action('vsplit')

" unite-grepの候補最大数を設定します。
let g:unite_source_grep_max_candidates=10000





""""""""""
" その他の環境設定

if has("unix")
  set backupdir=~/tmp
elseif has("win32")
  set backupdir=~/tmp
endif

nnoremap ; :

" インサートモードからノーマルモードへの切り替えを楽にします。
inoremap <C-j> <ESC>
