(defalias 'bcf 'byte-compile-file)
(defalias 'lf 'load-file)
(defalias 'lt 'load-theme)
(defalias 'obm 'occur-by-moccur)
(defalias 'plp 'package-list-packages)
(defalias 'plpn 'package-list-packages-no-fetch)
(defalias 'qrr 'query-replace-regexp) ; 正規表現置換
(defalias 'rb 'revert-buffer)
(defalias 'ssn 'shell-switcher-new-shell)
(defalias 'tff 'toggle-frame-fullscreen)
(defalias 'tfm 'toggle-frame-maximized)
